[DEFAULT]
snipe_url = https://your-snipe-it/api/v1
snipe_token = YOUR_SNIPE_API_KEY
jamf_url = https://your.jamf.instance.com
jamf_user = your_jamf_api_user
jamf_password = your_jamf_api_password
site_id = 1
company_id = 1
