[DEFAULT]
snipe_url = https://yoursnipe.it/api/v1
snipe_token = YOUR_SNIPE_API_KEY
site_id = 1
company_id = 1
sync_fields = hostname,os_name,os_version,os_build,mac_address,serial,logged_in_users,ad_group,asset_tag
