[DEFAULT]
snipe_url = https://yoursnipe.it/api/v1
snipe_token = YOUR_SNIPE_API_KEY
jamf_url = https://yourjamf.instance.com
jamf_user = JAMF_API_USER
jamf_password = JAMF_API_PASS
site_id = 1
company_id = 1
